language: python
python:
  - "3.6"

env:
  global:
   - GIT_COMMITTER_NAME="SymbiYosys Travis Bot"
   - GIT_COMMITTER_EMAIL="nobody@nowhere.com"

before_install:
  - ./.travis/save-key.sh
  - ./.travis/fix-git.sh

install:
  - pip install -r ./.travis/requirements.txt

script:
  - ./.travis/generate-html.sh

after_success:
  - if [ -e ~/.ssh/agent.sh ]; then source ~/.ssh/agent.sh; ./.travis/push-html.sh; fi
